import { NextRequest, NextResponse } from "next/server";
import { callAI, type ChatMessage } from "@/lib/eligibility/ai";
import { readOverrides } from "@/lib/api-overrides";
import { STATE_NAMES, SUPPORTED_STATES, type StateCode } from "@/lib/eligibility/types";

export const runtime = "nodejs";
export const maxDuration = 60;

interface Body {
  state?: string;
  documentExcerpt?: string;
  reportSummary?: string;
  history?: { role: "user" | "assistant"; content: string }[];
}

const SYSTEM_PROMPT = (state: StateCode | undefined, hasReport: boolean) => `
You are EduHelp's document Q&A assistant. The parent has uploaded an evaluation, IEP, doctor letter, or test report${
  state ? ` for a child in ${STATE_NAMES[state]}` : ""
} and wants to ask follow-up questions.

Rules:
- Answer ONLY based on the document text provided below. If the document doesn't say, say so plainly.
- Quote the exact sentence(s) from the document when you can.
- Keep answers short, plain-spoken, and parent-friendly (under ~200 words).
- Never invent statutes, scores, or diagnoses that aren't in the document.
- If the parent asks legal advice, redirect them to a state P&A or family resource center.
${hasReport ? "- An eligibility report has been generated by EduHelp's rules engine; you can reference its findings." : ""}
`.trim();

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as Body;
    const overrides = readOverrides(req);

    if (!body?.documentExcerpt?.trim()) {
      return NextResponse.json(
        { error: "No document excerpt was provided. Run /analyze first, then ask follow-up questions." },
        { status: 400 },
      );
    }
    if (!body.history || body.history.length === 0) {
      return NextResponse.json(
        { error: "No question to answer." },
        { status: 400 },
      );
    }
    const state =
      body.state && SUPPORTED_STATES.includes(body.state.toUpperCase() as StateCode)
        ? (body.state.toUpperCase() as StateCode)
        : undefined;

    const messages: ChatMessage[] = [
      {
        role: "system",
        content:
          SYSTEM_PROMPT(state, Boolean(body.reportSummary)) +
          "\n\nDOCUMENT EXCERPT (truncated):\n\n" +
          body.documentExcerpt.slice(0, 12000) +
          (body.reportSummary
            ? "\n\nELIGIBILITY REPORT SUMMARY:\n\n" + body.reportSummary.slice(0, 4000)
            : ""),
      },
      ...body.history.slice(-12),
    ];

    const resp = await callAI(messages, overrides, 800);
    return NextResponse.json({
      ok: true,
      message: resp.text,
      provider: resp.provider,
      model: resp.model,
    });
  } catch (err) {
    console.error("[EduHelp] chat error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Chat failed." },
      { status: 500 },
    );
  }
}
